name: embla_templates
description: Templating platform for Embla
version: 0.1.3
author: Emil Persson <emil.n.persson@gmail.com>
homepage: https://github.com/emilniklas/embla_templates

environment:
  sdk: ">=1.12.0 <2.0.0"

dependencies:
  embla: ^0.1.12
  path: ^1.3.9
  mustache: ^0.2.5
  async: ^1.8.0

dev_dependencies:
  test: any
  quark: any

dependency_overrides:
  embla:
    path: ../embla
